name = "json"
type = "javascript"
compatibility_date = "2022-02-01"
main="./dist/worker.js"
account_id = "d960779d52286b399fa007d93a7e2e21"

workers_dev = true

# kv_namespaces = [ 
#   { binding = "DOCUMENTS", id = "8c6a9a71fc504abdaaa7aa409c7b2abd" }
# ]

[vars]
GRAPH_JSON_COLLECTION = "jsonhero-dev"

[site]
bucket = "./public"

[build]
command = "npm run build:worker"
watch_dir = "build/index.js"

[build.upload]
format="service-worker"

[env.production]
route = "json.shanyue.tech/*"
zone_id = "af3c12add61e94b88b3d2cbfb6f65782"
# kv_namespaces = [ 
#   { binding = "DOCUMENTS", id = "e517c369774a443eba95afff9128f7b6" }
# ]

[env.production.vars]
GRAPH_JSON_COLLECTION = "jsonhero-prod"
SESSION_SECRET = "abc123"


# Secrets
# [SESSION_STORAGE]
# [GRAPH_JSON_API_KEY]
# [PEEKALINK_API_KEY]